apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-go-web-app
  labels:
    app: simple-go-web-app
spec:
  replicas: 3
  selector:
    app: simple-go-web-app
  template:
    metadata:
      labels:
        app: simple-go-web-app
    spec:
      containers:
      - name: simple-go-web-app
        image: "brianhhq/simple-go-web-app"
        ports:
        - containerPort: 8080
          name: http-server
